development:
  adapter: postgresql
  database: demo_app
  pool: 5
  timeout: 5000
  username: 'phithang'
  password: '123456'
test:
  adapter: postgresql
  database: demo_app
  pool: 5
  timeout: 5000
  username: 'phithang'
  password: '123456'


production:
  adapter: postgresql
  database: demo_app
  pool: 5
  timeout: 5000
  username: 'phithang'
  password: '123456'